### ISSUE TITLE
Naming: hackage-overlay-tool

### ISSUE THREAD

**Issue by angerman** [hvr/hackage-overlay-repo-tool#2]
I believe, we should rename this to `hackage-overlay-tool` or something. Right now it hardcodes "head.hackage", which is too specific I feel. Especially as it can be used for arbitrary overlays, of which head.hackage is just one instance.

**Comment by angerman** [comment]
ping?

**Comment by hvr** [comment]
I renamed the repo... how does it sound now?

**Comment by angerman** [comment]
That's a mouthful. But alright. No hardcoded "head.hackage" anymore :)
