### ISSUE TITLE
Do we need the cabal.cfg file

### ISSUE THREAD

**Issue by angerman** [hvr/hackage-overlay-repo-tool#3]
Or can we generate that just in time? It seem we are
using it only for
```
  -- pre-fetch packages
  run_ "cabal"  ["--config-file=" <> toTextIgnore (_cabal_cfg config), "update"]
  run_ "cabal" (["--config-file=" <> toTextIgnore (_cabal_cfg config), "fetch", "--no-dependencies"] ++
                map pid2txt (Set.toList $ cabalFns0 <> patchFns))
```

However, we do have the `repo_cache` and `repo_name` in the config already, shouldn't we as such be able to simply generate the `cabal.cfg` file?

```
repository $repo_name
  url: http://hackage-origin.haskell.org/
  secure: True

http-transport: plain-http
remote-repo-cache: $repo_cache
```

we would probably need `repo_url` as well though.

**Comment by angerman** [comment]
What kind of irks me, is that you need to specify the path to the `cabal.cfg` *and* the repo_name and repo_cache, which seems rather redundant and prone to produce issues :(

**Comment by hvr** [comment]
I'm fine with generating it...

**Comment by angerman** [comment]
I'll put this into #1, and then we merge, ok?
